Update Command-T
vim-plugins/command-t tip:

    commit ce9daf8d792c945d32d0bf8878149eaa8aee2b81
    Author: Greg Hurrell <greg@hurrell.net>
    Date:   Sun Jan 8 14:05:38 2017 +1030

        Revert Gem::Ext::BuildError change

        I tested this in `irb`, but when I ran Command-T, it dies with:

          NameError: uninitialized constant Gem::Ext

        So will have to try again.